### ISSUE TITLE
环境版本

### ISSUE THREAD

**Issue by tkone2018** [nipponjo/deepfillv2-pytorch#1]
你好，感谢你的分享，想咨询一下可以说一下你当前环境的版本吗 特别是torch版本，我这边不知道是版本高了还是低了，报错

**Comment by nipponjo** [comment]
你好, I used the following versions for testing: python==3.9.1 torch==1.10.0+cu113 torchvision==0.11.1+cu113 tensorboard==2.7.0 numpy==1.21.1 pyyaml==5.4.1 Pillow==8.3.1

**Comment by tkone2018** [comment]
@nipponjo 好的，谢谢

**Comment by tkone2018** [comment]
@nipponjo Traceback (most recent call last):
  File "/app/deepfillv2-pytorch-master/test.py", line 80, in <module>
    main()
  File "/app/deepfillv2-pytorch-master/test.py", line 36, in main
    generator.load_state_dict(generator_state_dict)
  File "/opt/conda/envs/deepfill/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1482, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Generator:
	Missing key(s) in state_dict: "stage1.conv1.conv.weight", "stage1.conv1.conv.bias", "stage1.down_block1.conv1_downsample.conv.weight", "stage1.down_block1.conv1_downsample.conv.bias", "stage1.down_block1.conv2.conv.weight", "stage1.down_block1.conv2.conv.bias", "stage1.down_block2.conv1_downsample.conv.weight", "stage1.down_block2.conv1_downsample.conv.bias", "stage1.down_block2.conv2.conv.weight", "stage1.down_block2.conv2.conv.bias", "stage1.conv_bn1.conv.weight", "stage1.conv_bn1.conv.bias", "stage1.conv_bn2.conv.weight", "stage1.conv_bn2.conv.bias", "stage1.conv_bn3.conv.weight", "stage1.conv_bn3.conv.bias", "stage1.conv_bn4.conv.weight", "stage1.conv_bn4.conv.bias", "stage1.conv_bn5.conv.weight", "stage1.conv_bn5.conv.bias", "stage1.conv_bn6.conv.weight", "stage1.conv_bn6.conv.bias", "stage1.conv_bn7.conv.weight", "stage1.conv_bn7.conv.bias", "stage1.up_block1.conv1_upsample.conv.conv.weight", "stage1.up_block1.conv1_upsample.conv.conv.bias", "stage1.up_block1.conv2.conv.weight", "stage1.up_block1.conv2.conv.bias", "stage1.up_block2.conv1_upsample.conv.conv.weight", "stage1.up_block2.conv1_upsample.conv.conv.bias", "stage1.up_block2.conv2.conv.weight", "stage1.up_block2.conv2.conv.bias", "stage1.conv_to_rgb.conv.weight", "stage1.conv_to_rgb.conv.bias", "stage2.conv_conv1.conv.weight", "stage2.conv_conv1.conv.bias", "stage2.conv_down_block1.conv1_downsample.conv.weight", "stage2.conv_down_block1.conv1_downsample.conv.bias", "stage2.conv_down_block1.conv2.conv.weight", "stage2.conv_down_block1.conv2.conv.bias", "stage2.conv_down_block2.conv1_downsample.conv.weight", "stage2.conv_down_block2.conv1_downsample.conv.bias", "stage2.conv_down_block2.conv2.conv.weight", "stage2.conv_down_block2.conv2.conv.bias", "stage2.conv_conv_bn1.conv.weight", "stage2.conv_conv_bn1.conv.bias", "stage2.conv_conv_bn2.conv.weight", "stage2.conv_conv_bn2.conv.bias", "stage2.conv_conv_bn3.conv.weight", "stage2.conv_conv_bn3.conv.bias", "stage2.conv_conv_bn4.conv.weight", "stage2.conv_conv_bn4.conv.bias", "stage2.conv_conv_bn5.conv.weight", "stage2.conv_conv_bn5.conv.bias", "stage2.ca_conv1.conv.weight", "stage2.ca_conv1.conv.bias", "stage2.ca_down_block1.conv1_downsample.conv.weight", "stage2.ca_down_block1.conv1_downsample.conv.bias", "stage2.ca_down_block1.conv2.conv.weight", "stage2.ca_down_block1.conv2.conv.bias", "stage2.ca_down_block2.conv1_downsample.conv.weight", "stage2.ca_down_block2.conv1_downsample.conv.bias", "stage2.ca_down_block2.conv2.conv.weight", "stage2.ca_down_block2.conv2.conv.bias", "stage2.ca_conv_bn1.conv.weight", "stage2.ca_conv_bn1.conv.bias", "stage2.ca_conv_bn4.conv.weight", "stage2.ca_conv_bn4.conv.bias", "stage2.ca_conv_bn5.conv.weight", "stage2.ca_conv_bn5.conv.bias", "stage2.conv_bn6.conv.weight", "stage2.conv_bn6.conv.bias", "stage2.conv_bn7.conv.weight", "stage2.conv_bn7.conv.bias", "stage2.up_block1.conv1_upsample.conv.conv.weight", "stage2.up_block1.conv1_upsample.conv.conv.bias", "stage2.up_block1.conv2.conv.weight", "stage2.up_block1.conv2.conv.bias", "stage2.up_block2.conv1_upsample.conv.conv.weight", "stage2.up_block2.conv1_upsample.conv.conv.bias", "stage2.up_block2.conv2.conv.weight", "stage2.up_block2.conv2.conv.bias", "stage2.conv_to_rgb.conv.weight", "stage2.conv_to_rgb.conv.bias". ，你好，帮忙看下，好像是模型不太对？谢谢

**Comment by tkone2018** [comment]
@nipponjo load model error

**Comment by nipponjo** [comment]
The pretrained weights only work with the models in 'networks_tf.py'. You can include --tfmodel e.g: 

python test.py --tfmodel --image examples/inpaint/case1.png --mask examples/inpaint/case1_mask.png --out examples/inpaint/case1_out_test.png --checkpoint pretrained/states_tf_places2.pth

to test with the pretrained weights.

**Comment by tkone2018** [comment]
@nipponjo  ok, thank u
