### ISSUE TITLE
Where can I download the states_tf_places2.pth file?

### ISSUE THREAD

**Issue by ChiwoongLEE** [nipponjo/deepfillv2-pytorch#14]
If you read Readme, you can download it through the link below, but there is no pth file if you download and unzip it.

https://drive.google.com/u/0/uc?id=1tvdQRmkphJK7FYveNAKSMWC6K09hJoyt&export=download

**Comment by nipponjo** [comment]
Hello, you don't need to unzip the file. You can directly load it using `torch.load('states_tf_places2.pth')`.

**Comment by ChiwoongLEE** [comment]
Where should I load the code?

I'm sorry, but can you explain it in more detail?
