### ISSUE TITLE
Pretrained models

### ISSUE THREAD

**Issue by srayan00** [nipponjo/deepfillv2-pytorch#22]
What data set was used to train the places and celebahq model?

**Comment by nipponjo** [comment]
Hello, 
the paper cites:
`[53] Bolei Zhou, Agata Lapedriza, Aditya Khosla, Aude Oliva, and Antonio Torralba. Places: A 10 million image database for scene recognition. IEEE Transactions on Pattern Analy- sis and Machine Intelligence, 2017. 3, 6` 
for the Places dataset and 
`[18] Tero Karras, Timo Aila, Samuli Laine, and Jaakko Lehtinen. Progressive growing of gans for improved quality, stability, and variation. arXiv preprint arXiv:1710.10196, 2017. 3, 6`
for the CelebA-HQ dataset.

Therefore, I assume (http://places2.csail.mit.edu/) and (https://www.kaggle.com/datasets/lamsimon/celebahq) were used. I also used these for fine-tuning the weights.
