### ISSUE TITLE
training time and convergence

### ISSUE THREAD

**Issue by zhenzey** [nipponjo/deepfillv2-pytorch#4]
Thanks for the nice code! Could you given an estimate about the training time of the model on CeleBA-HQ and Places2 ? And how is the model's performances with a smaller dataset with, for instance, thousands of data?

**Comment by nipponjo** [comment]
Hi, there are a few questions/answers about this on the original repo e.g. https://github.com/JiahuiYu/generative_inpainting/issues/62#issuecomment-419734789. The model takes long to learn fine details like hair, so the training time much depends on the images. On a new dataset I would assume that it makes sense to start with the pretrained models. They can be used for fine-tuning with the models in `networks.py` by a simple renaming. 

```python
import torch
from model.networks import Generator, Discriminator

model_sds = torch.load('pretrained/states_tf_places2.pth')
gen_tf_sd = model_sds['G']
gen = Generator(cnum_in=5, cnum=48)
gen_state_dict = gen.state_dict()

for pt_key, tf_val in zip(gen_state_dict.keys(), gen_tf_sd.values()):
    gen_state_dict[pt_key].copy_(tf_val)

gen.load_state_dict(gen_state_dict)
model_sds['G'] = gen.state_dict()
torch.save(model_sds, 'pretrained/states_pt_places2.pth')
```

**Comment by zhenzey** [comment]
Thanks a lot for the clarification. I really appreciate it!

**Comment by nipponjo** [comment]
In case you are interested, a while ago I trained the models in `networks.py` on places2 for some time and in my tests they seemed to perform similarly (example on image). I don't know if these states are better suited, but here is the link: [states_pt_places2.pth](https://drive.google.com/uc?id=1ELurhKf4eaXBbkCl2WwdfYIxILenPj8o&export=download) :)

![Screenshot 2022-06-14 235816](https://user-images.githubusercontent.com/28433296/173702280-9d171780-730f-4e34-8efc-25d555849946.png)

**Comment by zhenzey** [comment]
Thanks for sharing, I will test the new checkpoints and the pre-training saves a lot of time

**Comment by juntaosun** [comment]
> 如果您有兴趣，不久前我在 places2 上训练了一段时间的模型，在我的测试中，它们似乎表现相似（图像示例）。我不知道这些州是否更适合，但这里是链接：[states_pt_places2.pth](https://drive.google.com/uc?id=1ELurhKf4eaXBbkCl2WwdfYIxILenPj8o&export=download) :)`networks.py`
> 
> ![Screenshot 2022-06-14 235816](https://user-images.githubusercontent.com/28433296/173702280-9d171780-730f-4e34-8efc-25d555849946.png)

states_pt_places2.pth  404, not download~找不到了，您的文件可以补一下吗

**Comment by nipponjo** [comment]
Hello, I put the link into the readme.
